version: 2
jobs:
  build:
    working_directory: ~/NetCoreExample
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: restore-packages
          command: 'dotnet restore'
      - run:
          name: code-coverage
          command: 'dotnet publish --output /out/ --configuration Release'
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t jarga/netcoreexample:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push jarga/netcoreexample:$TAG