version: 2
jobs:
  build:
    working_directory: ~/NetCoreExample
    docker:
      - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Restore Packages
          command: 'dotnet restore'
      - run:
          name: Build Artifacts
          command: 'dotnet publish -o ./publish --configuration Release'
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/netcoreexample:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push $DOCKER_USER/netcoreexample:$TAG