version: '3.1'
services:
    mongo:
        ports:
            - "27017:27017"
        image: "mongo:3"
        restart: on-failure
    rabbitmq:
        image: rabbitmq:3.6.1-management
        ports:
            - "15672:15672"
            - "5672:5672"
        restart: on-failure