version: '3.1'
services:
    mongo:
        image: "mongo:3"
        ports:
            - "27017:27017"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    rabbitmq:
        image: rabbitmq:3.6.1-management
        ports:
            - "15672:15672"
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    worker:
        image: "jarga/netcoreworkerexample:${TAG:-latest}"
        depends_on:
            - mongo
            - rabbitmq
        environment:
            - AmqpUri=amqp://guest:guest@rabbitmq:5672/
            - MongoUri=mongodb://mongo:27017/example
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
    app:
        image: "jarga/netcorewebexample:${TAG:-latest}"
        depends_on:
            - mongo
            - rabbitmq
        ports:
            - "80:80"
        environment:
            - AmqpUri=amqp://guest:guest@rabbitmq:5672/
            - MongoUri=mongodb://mongo:27017/example
        deploy:
            replicas: 1
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
